FROM node:10.19.0 as node
WORKDIR /app
COPY . .
RUN npm install
RUN npm run build

# https://stackoverflow.com/questions/45858957/404-not-found-nginx-angular-routing
RUN echo 'pushstate: enabled' > dist/Staticfile 

FROM nginx:alpine
COPY --from=node /app/dist/angularfrontend /usr/share/nginx/html
